tgbot
UncleSema/belfort pull request #20
Opened 2022-11-12 08:20 UTC by TsenreD

2022-11-12 08:47 UTC, UncleSema requested changes
Добавь логгирования на уровне debug/info, чтобы можно было отслеживать, когда нам приходят сообщения по логам

2022-11-12 08:47 UTC, UncleSema commented on telegram-service/src/main/java/ru/ct/belfort/RestApiController.java
> +            e.printStackTrace();
logger.error("Exception during registering bot", e)

2022-11-12 08:47 UTC, UncleSema commented on telegram-service/src/main/java/ru/ct/belfort/tgbot/TelegramBot.java
> +    private final String BOT_TOKEN = "5749489834:AAFKqXzbjBxkrG0xt5mjtqGtTXKOA2Hdqzo";
Ай-яй-яй!
Создай переменную окружения BOT_TOKEN и вычитывай её при помощи System.getenv("BOT_TOKEN"). Добавь её себе в конфигурации запуска в idee

2022-11-12 08:47 UTC, UncleSema commented on telegram-service/src/main/java/ru/ct/belfort/tgbot/AbstractCommand.java
> +            e.printStackTrace();
Аналогично

2022-11-12 08:47 UTC, UncleSema commented on telegram-service/src/main/java/ru/ct/belfort/tgbot/TelegramBot.java
> +            e.printStackTrace();
Аналогично

2022-11-12 16:55 UTC, TsenreD commented on telegram-service/src/main/java/ru/ct/belfort/tgbot/TelegramBot.java
> +    private final String BOT_TOKEN = "5749489834:AAFKqXzbjBxkrG0xt5mjtqGtTXKOA2Hdqzo";
+

2022-11-12 16:55 UTC, TsenreD commented on telegram-service/src/main/java/ru/ct/belfort/RestApiController.java
> +            e.printStackTrace();
+

2022-11-12 16:55 UTC, TsenreD commented on telegram-service/src/main/java/ru/ct/belfort/tgbot/AbstractCommand.java
> +            e.printStackTrace();
+

2022-11-12 16:55 UTC, TsenreD commented on telegram-service/src/main/java/ru/ct/belfort/tgbot/TelegramBot.java
> +            e.printStackTrace();
+

2022-11-18 09:32 UTC, UncleSema approved these changes

2022-11-18 09:34 UTC, merged